// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class FirebaseConfigApp {
  static Future initializeFirebase() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhBFroXY1u7e4c1_leUSiDsxFoEpuS6g8',
    appId: '1:967298819931:android:37478854d16c585b955c7e',
    messagingSenderId: '967298819931',
    projectId: 'all-in-one-fea38',
    storageBucket: 'all-in-one-fea38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    storageBucket: '',
    iosBundleId: '',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyD1CY1lZ-4QpFE743cWDWdyA0L7cWSDPjA",
      authDomain: "all-in-one-fea38.firebaseapp.com",
      databaseURL: "https://all-in-one-fea38-default-rtdb.firebaseio.com",
      projectId: "all-in-one-fea38",
      storageBucket: "all-in-one-fea38.firebasestorage.app",
      messagingSenderId: "967298819931",
      appId: "1:967298819931:web:1776eff41df12601955c7e",
      measurementId: "G-CWCJFE5KKB");
}
